---
- name: debug package variable
  debug:
    var: package

- name: "1、停止残留的filebeat"
  ignore_errors: true
  systemd:
    name: filebeat
    state: stopped
  become: true

- name: "2、清理可能的filebeat service残留文件"
  file:
    path: /etc/systemd/system/filebeat.service
    state: absent
  become: true

- name: "3、清理可能的filebeat残留文件夹"
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ filebeat_install_path }}/{{ filebeat_link }}'
    - '{{ filebeat_install_path }}/filebeat-{{ filebeat_version }}'

- name: "4、创建临时目录"
  file: dest={{ tmp_dir }} state=directory

- name: "5、拷贝filebeat二进制包"

  copy: src={{ software_dir }}/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz dest={{ tmp_dir }}
  when: hostvars[inventory_hostname]['package'] == "true"

- name: "5、下载filebeat二进制包"
  get_url:
    url: "https://artifacts.elastic.co/downloads/filebeat/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz"
    validate_certs: false
    dest: "{{ tmp_dir }}"
    mode: "0644"
    force: true
  when: hostvars[inventory_hostname]['package'] == "false"

- name: "6、解压filebeat二进制包"
  unarchive: src={{ tmp_dir }}/filebeat-{{ filebeat_version }}-linux-x86_64.tar.gz dest={{ tmp_dir }} remote_src=true

- name: "7、移动filebeat二进制包"
  command: mv {{ tmp_dir }}/filebeat-{{ filebeat_version }}-linux-x86_64 {{ filebeat_install_path }}/filebeat-{{ filebeat_version }}

- name: "8、生成filebeat.yml配置文件"
  template:
    src: "filebeat.yml.j2"
    dest: "{{ filebeat_install_path }}/filebeat-{{ filebeat_version }}/filebeat.yml"

- name: "9、创建链接文件"
  file:
    src: "{{ filebeat_install_path }}/filebeat-{{ filebeat_version }}"
    dest: "{{ filebeat_install_path }}/{{ filebeat_link }}"
    state: link

# - name: "10、修改目录权限"
#   file: 
#     path: "{{ item }}"
#     owner: "{{ filebeat_install_user }}"
#     group: "{{ filebeat_install_user }}"
#     state: directory
#   with_items:
#     - "{{ filebeat_install_path }}/filebeat-{{ filebeat_version }}"

- name: "10、配置systemd守护进程"
  template: src=filebeat.service.j2 dest=/etc/systemd/system/filebeat.service

# - name: "12、启动filebeat服务"
#   systemd:
#     name: filebeat
#     state: started
#     daemon_reload: yes
#     enabled: yes
