---
- name: debug package variable
  debug:
    var: package

- name: "1、停止残留的nginx"
  ignore_errors: true
  systemd:
    name: nginx
    state: stopped
  become: true

- name: "2、清理可能的nginx service残留文件"
  file:
    path: /etc/systemd/system/nginx.service
    state: absent
  become: true

- name: "3、清理可能的nginx残留文件夹"
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ nginx_work_dir }}'
    
- name: "4、创建临时目录"
  file: dest={{ tmp_dir }} state=directory

- name: "5、拷贝nginx安装包"
  copy: src={{ software_dir }}/nginx-{{ nginx_version }}.tar.gz dest={{ tmp_dir }}
  when: hostvars[inventory_hostname]['package'] == "true"

- name: "5、下载nginx二进制包"
  get_url:
    url: "https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
    validate_certs: false
    dest: "{{ tmp_dir }}"
    mode: "0644"
    force: true
  when: hostvars[inventory_hostname]['package'] == "false"

- name: "6、解压nginx源码"
  unarchive: src={{ tmp_dir }}/nginx-{{ nginx_version }}.tar.gz dest={{ tmp_dir }} remote_src=true

- name: "7、安装编译器"
  package:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libpcre3-dev
    - libssl-dev

- name: "8、创建{{ nginx_install_user }}用户"
  user:
    name: nginx
    shell: /sbin/nologin

- name: "9、编译安装nginx"
  shell: cd {{ tmp_dir }}/nginx-{{ nginx_version }} && ./configure --prefix={{ nginx_work_dir }} --user={{ nginx_install_user }} --group={{ nginx_install_user }}--with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' && make  && make install
  changed_when: false

- name: "10、拷贝nginx配置文件"
  template: src=nginx.conf.j2 dest={{ nginx_work_dir }}/conf/nginx.conf

- name: "11、拷贝nginx.service文件"
  template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service

- name: "12、启动nginx服务"
  ignore_errors: true
  systemd: name={{ item }} state=restarted enabled=yes daemon_reload=yes
  with_items:
    - nginx

- name: "13、测试访问nginx"
  ansible.builtin.uri:
    url: "http://127.0.0.1:8003/ngx_status"
    return_content: true
    status_code: 200
  register: curl_info

- name: "14、打印请求信息"
  ansible.builtin.debug:
    var: curl_info.msg
  changed_when: false
