---
- name: debug package variable
  debug:
    var: package

- name: "1、清理可能的maven残留文件夹"
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ maven_install_path }}/{{ maven_link }}'
    - '{{ maven_install_path }}/apache-maven-{{ maven_version }}'

- name: "2、创建临时目录"
  file: dest={{ tmp_dir }} state=directory

- name: "3、拷贝maven二进制包"
  copy: src={{ software_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz dest={{ tmp_dir }}
  when: hostvars[inventory_hostname]['package'] == "true"

- name: "3、下载maven二进制包"
  get_url:
    url: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    validate_certs: false
    dest: "{{ tmp_dir }}"
    mode: "0644"
    force: true
  when: hostvars[inventory_hostname]['package'] == "false"

- name: "4、解压maven二进制包"
  unarchive: src={{ tmp_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz dest={{ tmp_dir }} remote_src=true

- name: "5、移动jdk二进制包"
  command: mv {{ tmp_dir }}/apache-maven-{{ maven_version }} {{ maven_install_path }}

- name: "6、创建链接文件"
  file:
    src: "{{ maven_install_path }}/apache-maven-{{ maven_version }}"
    dest: "{{ maven_install_path }}/{{ maven_link }}"
    state: link

- name: "7、生成环境变量配置文件"
  template:
    src: "maven.sh.j2"
    dest: "/etc/profile.d/maven.sh"

- name: "8、加载配置文件"
  shell: . /etc/profile.d/maven.sh

# - name: "7、set the MAVEN_HOME environment"
#   lineinfile: dest=/etc/profile regexp="^export JAVA_HOME=" line="export JAVA_HOME={{ jdk_path }}/{{ jdk_link }}\nexport MAVEN_HOME={{ maven_install_path }}/{{ maven_link }}"

# - name: "8、set the PATH environment"
#   lineinfile: dest=/etc/profile regexp="^export PATH=\$PATH:" line="export PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin"

# - name: "9、加载配置文件"
#   shell: . /etc/profile
