---
- name: "1、创建临时目录"
  file: dest={{ tmp_dir }} state=directory

- name: "2、拷贝jdk二进制包"
  copy: src={{ software_dir }}/{{ jdk_version }} dest={{ tmp_dir }}

- name: "3、解压jdk二进制包"
  unarchive: src={{ tmp_dir }}/{{ jdk_version }} dest={{ tmp_dir }}

- name: "4、移动jdk二进制包"
  command: mv {{ tmp_dir }}/{{ jdk_work_dir }} {{ jdk_path }}

- name: "5、创建链接文件"
  file:
    src: "{{ jdk_path }}/{{ jdk_work_dir }}"
    dest: "{{ jdk_path }}/{{ jdk_link }}"
    state: link

- name: "6、set the JAVA_HOME environment"
  lineinfile: dest=/etc/profile regexp="^export JAVA_HOME=" line="export JAVA_HOME={{ jdk_path }}/{{ jdk_link }}"

- name: "7、set the PATH environment"
  lineinfile: dest=/etc/profile regexp="^export PATH=\$PATH:" line="export PATH=$PATH:$JAVA_HOME/bin"

- name: "8、加载配置文件"
  shell: . /etc/profile
