---
- name: Demonstrate warning filter plugin
  gather_facts: no
  hosts: all

  tasks:
    - meta: end_play
      when: ('file XYZ cannot be processed' | warning())
      delegate_to: localhost
      run_once: yes
